Support for benchmarking of diffusion models
ml-energy/leaderboard-v2 pull request #31
Opened 2024-01-08 21:25 UTC by SchwarzXia

This PR includes the current progress on the benchmark script for diffusion models. The scripts are located in `scripts/diffusion/` and `benchmark.Dockerfile` is modified to add dependency for HF diffusers.

### How to run
After building the container, use this to run the container:
```
docker run -it \
    --name diffusion \
    -v /data/diffusion:/data/leaderboard/hfcache \
    --gpus '"device=0"' \
    --env NVIDIA_DISABLE_REQUIRE=1 \
    diffusion-benchmark bash
```

The script can be run either from command line:
```
python3 benchmark.py --model "runwayml/stable-diffusion-v1-5" --prompt_size 128 --batch_size 2
```

or through calling from another python script:
```
benchmark("runwayml/stable-diffusion-v1-5", prompt_size=32, batch_size=8, settings={"num_inference_steps":20})
```

### TODO
We need to figure out how to merge this script with current LLM benchmarking, and how to present the data.

2024-01-09 14:10 UTC, jaywonchung requested changes
Thanks for your work! I left some comments.

I tend to be very strict especially on the first couple PR reviews I do for my intern students. But I do believe that all this is worth your time; good code quality never betrays you in your career. Also, code that is open-sourced represents our skill level. We should be proud of the code we put out there, instead of just aiming to get it done ASAP and forget about it.

Let me know if there's anything I can clarify more to help you. I'll do another review after you've addressed current comments. Please click "Request" next to my name in the "Reviewers" sidebar on the right to notify me.

2024-01-09 14:10 UTC, jaywonchung commented on deployment/benchmark.Dockerfile
> +RUN pip install datasets diffusers transformers accelerate torchmetrics[image] zeus-ml tyro
Please move these dependencies into `pyproject.toml` > `extras_require` > `"benchmark"` so that line 23 will automatically install everything needed.

2024-01-09 14:10 UTC, jaywonchung commented on deployment/benchmark.Dockerfile
> +ENV HF_HOME=/data/leaderboard/hfcache
What does this do in addition to `TRANSFORMERS_CACHE`?

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +from metrics import *
Imports should be ordered and grouped in three blocks separated in a newline:
1. Built-in modules (gc)
2. External packages (torch, tyro, numpy, diffusers, zeus)
3. Local modules (utils, metrics)

Also, do not do wildcard imports since they significantly reduce readability and may have unexpected name collision issues when there are more than one. Explicitly list the things imported from `metrics`.

This comment applies to all Python files in this PR.

See: https://google.github.io/styleguide/pyguide.html#313-imports-formatting

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +        return pipeline.from_pretrained(model, torch_dtype=weight_dtype, safety_checker = None).to(device)
This function has a lot of room for improvement IMO.
1. When do you need `DiffusionPipeline` vs. `AutoPipelineForText2Image`? The code should be explicit about when which one is used. Plus, are you sure the two have the same performance/energy characteristics? If they have vastly different implementation, performance and energy will also be different. Which one has been used should be recorded in the results file. The best way is to figur out how to use only one of them for everything.
2. The fallback to `pipeline` is based on a broad `except`, which is [strongly discouraged](https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/broad-exception-caught.html). This is what is obscuring control flow here.
3. If a user explicitly passed in an argument to `pipeline` when calling `get_pipeline`, wouldn't they want the `pipeline` to be used to instantiate the pipeline instead of `AutoPipelineForText2Image`?

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +    monitor = ZeusMonitor(gpu_indices=[torch.cuda.current_device()])
I think `torch.cuda.current_device()` only returns what you expect if you called `torch.cuda.set_device(device)` before it.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +    """
We need parameter docstrings here for `tyro` to parse. Follow the Google style: https://google.github.io/styleguide/pyguide.html#doc-function-args. Especially, you need to document what `settings` can hold. I also don't get what `prompt_size` means, which means it probably needs a better name. I also don't get what `prompt_size` is, which means it probably needs a better name.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +        gpu_warmup()
We should warm up for maybe like 10 seconds. Please call `gpu_warmup` multiple times.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +    pipeline = get_pipeline("runwayml/stable-diffusion-v1-5")
Warm ups should be done with the **exact same** model and data format we will be benchmarking. Otherwise it's not effective.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +    pipeline = get_pipeline("runwayml/stable-diffusion-v1-5")
Plus, this warm up function creates a Stable Diffusion v1.5 pipeline, puts it in VRAM, and does not explicitly remove it before returning, which means that we're relying on the Python garbage collector to free the memory for the warmup-only pipeline (which is at a random timing). Total memory allocation also affects computation performance and energy consumption, so this warmup function is introducing non-trivial noise into the benchmarking process.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/metrics.py
> +def load_prompts_clip(size, batch_size, seed):
Another very confusing function signature.
1. We're measuring everything from parti-prompts, so the word `clip` in the function name is confusing. Please rename this to `load_prompts`.
2. `size` should be renamed to `num_prompts`.
3. `size == 0` meaning "everything" should be documented.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/metrics.py
> +        random.seed(seed)
You would have seeded this in the main function with the snippet I provided, so remove.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/metrics.py
> +    prompts = [prompts[i]["Prompt"] for i in range(size)]
```suggestion
    prompts = [prompt["Prompt"] for prompt in prompts[:size]]
```
Indexing with `i` every time is time-consuming. I think I see a couple more of this inefficiency in this file.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/metrics.py
> +    return ([random.choice(prompts[i]["caption"]) for i in range(size)], [prompts[i]["image"] for i in range(size)])
Remove unused functions.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +
If we were to literally save all the images we generated for each model, how much disk space would that be? If that's a reasonable size (since parti-prompts isn't that large) maybe we should save everything. We also want to sanity check whether all our pipelines are running correctly by visually inspecting at least a subset of the images generated.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +        'peak_memory' : round(peak_memory/1024/1024/1024, 4)
Do not truncate information at the time of saving (I'm referring to `round`). We can do this later when we process results.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +    tyro.cli(benchmark)
All files should end with a newline, as per UNIX convention. There's probably a setting in your editor that says "line ending." You should use `LF`.

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/metrics.py
> +    return round(float(clip), 2)
Remove `round`; ditto of previous comment

2024-01-09 14:10 UTC, jaywonchung commented on scripts/diffusion/utils.py
> +        except Exception as e:
Remove all try-excepts in this class (Plus, you will now see that they're smelly broad excepts). I believe it is not your intention to print "Error opening file" and then continue program execution; you want the program to just die on such error. That is what exceptions do. Remove the try-except and let the program die. It'll report where it died too via traceback, so you will know which line raised the exception.

2024-01-09 14:11 UTC, jaywonchung commented
One more question: Why do we need `--env NVIDIA_DISABLE_REQUIRE=1`?

2024-01-12 07:17 UTC, SchwarzXia commented on deployment/benchmark.Dockerfile
> +ENV HF_HOME=/data/leaderboard/hfcache
Diffusers library doesn't use `TRANSFORMERS_CACHE` to mark where to place downloaded models, so we need to set `HF_HOME` for this (https://huggingface.co/docs/diffusers/installation#cache)

2024-01-12 07:20 UTC, SchwarzXia commented on scripts/diffusion/benchmark.py
> +        return pipeline.from_pretrained(model, torch_dtype=weight_dtype, safety_checker = None).to(device)
The current idea is that we let the Diffuser library choose the default/best pipeline for each model (note that neither `DiffusionPipeline` nor `AutoPipelineForText2Image` are pipeline implementations, they just autos to the pipeline of each model, where are supposed to be different). 
However neither of these two supports all models we are benchmarking, and there isn't an easy way to check if one supports one model or not, so I believe I have to keep this try-except.

2024-01-12 07:22 UTC, SchwarzXia commented on scripts/diffusion/metrics.py
> +        random.seed(seed)
So it turns out that I was doing this wrong and the `shuffle()` should use `np`'s RNG instead. This has been fixed to work correctly.

2024-01-12 07:25 UTC, SchwarzXia commented on scripts/diffusion/benchmark.py
> +
Each image is ~350kb, so totals about ~560mb per model.

2024-01-12 07:27 UTC, SchwarzXia commented
> One more question: Why do we need `--env NVIDIA_DISABLE_REQUIRE=1`?

This was to fix an issue with the fact that the server had an older CUDA driver (11.8). This should not be an issue now as we're using `torch==2.0.1` in `setup.py`.

2024-01-12 15:19 UTC, jaywonchung commented on setup.py
> +                  "datasets", "diffusers", "transformers", "accelerate", "torchmetrics[image]"],
Versions should be pinned with `==` for the new packages, since this aims to be a reproducible benchmarking package.

2024-01-12 15:19 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +        return pipeline.from_pretrained(model, torch_dtype=weight_dtype, safety_checker = None).to(device)
The Diffusers documentations says that `DiffusionPipeline` is the simplest and most generic way of loading diffusion models from the Hub ([link](https://huggingface.co/docs/diffusers/v0.25.0/en/using-diffusers/loading#diffusion-pipeline)). Which model doesn't support `DiffusionPipeline`? Also could you create `pegasus/diffusion-benchmark.yaml` that lists all the models we'll benchmark? You can copy and modify `pegasus/benchmark.yaml`.

2024-01-12 15:29 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +    monitor = ZeusMonitor(gpu_indices=[torch.tensor(0,device=device).get_device()])
```suggestion
    torch.cuda.set_device(device)
    monitor = ZeusMonitor(gpu_indices=[torch.cuda.current_device()])
```

2024-01-12 15:29 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +    logger.info("Finished warming up GPU")
This still does not solve the memory issue. You instantiated a warmup-only pipeline on line 35 and threw it away after you're done. This is wrong because
1. It's extra unfreed memory that is not going to participate in actual benchmarking
2. When you start real benchmarking, the new pipeline you loaded on line 94 will be "cold"

Instead you should load only one pipeline on line 94 and then pass that into `gpu_warmup` and use it.

2024-01-12 15:29 UTC, jaywonchung commented on scripts/diffusion/metrics.py
> +        random.seed(seed)
Oh apparently during the GItHub outage I think one of my comments got lost. "The snippet I provided" is: https://github.com/huggingface/transformers/blob/main/src/transformers/trainer_utils.py#L85-L105. The comment basically advises copy in the `set_seed` into our code and to replace the call to `torch.manual_seed` inside `benchmark` with `set_seed`.

2024-01-12 15:41 UTC, jaywonchung commented on scripts/diffusion/metrics.py
> +    return prompts, [prompts[i:i + batch_size] for i in range(0, len(prompts), batch_size)]
Please drop the final batch since it may be smaller than `batch_size`.

2024-01-12 15:41 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +        'avg_latency' : result_monitor.time/benchmark_size,
I think Mosharaf also mentioned this during the meeting. Average latency when batch size > 1 is meaningless. You should divide by how many batches were run, not `benchmark_size`. Also, add a `throughput` metric.

2024-01-12 15:41 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +        'image_num' : benchmark_size,
```suggestion
        'num_prompts' : benchmark_size,
```

2024-01-12 15:41 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +        'peak_memory' : peak_memory/1024/1024/1024,
```suggestion
        'peak_memory' : peak_memory,
```

2024-01-12 15:41 UTC, jaywonchung commented on scripts/diffusion/benchmark.py
> +
Hmm. Kinda large. I guess we can't save everything, but still please figure out a way to sanity check generations. One way would be to select 10% of the images generated and hold the corresponding prompt and generated numpy array in memory, and then when benchmarking is done, save everything to disk. We want to hold those in memory during benchmarking and dump everything in the end because saving to disk will make the loop slower and interfere with benchmarking. Also, you need to make sure you convert the image to a numpy array and discard the torch tensor, so that GPU memory is deallocated.

2024-01-12 15:43 UTC, jaywonchung requested changes
We're almost done. Thanks for your effort!

This time, just before you re-request review, run the `black` code formatter (pip install black) for all the Python files.

2024-01-13 05:26 UTC, SchwarzXia commented on scripts/diffusion/benchmark.py
> +        return pipeline.from_pretrained(model, torch_dtype=weight_dtype, safety_checker = None).to(device)
`kandinsky-community/kandinsky-2-2-decoder` doesn't work for `DiffusionPipeline`, while `kakaobrain/karlo-v1-alpha` and `CompVis/ldm-text2im-large-256` doesn't work for `AutoPipelineForText2Image`.

2024-01-13 23:15 UTC, jaywonchung approved these changes
Thanks @SchwarzXia! Looks all good to me. I'll handle some small nitpicks from here on and then merge.

2024-01-20 05:23 UTC, merged