Integrate Inteference Server-compatible Benchmark
ml-energy/leaderboard-v2 pull request #34
Opened 2024-02-02 02:49 UTC by ohjuny

Create a benchmark script that integrates with both Hugging Face TGI (Text Generation Inference) and vLLM.

2024-02-17 16:02 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +                break
Was this retry originally in vLLM's benchmarking script? Have you observed frequent request timeouts or failures?

To me, this is strange. With automatic retry after failure without bookkeeping, we end up running more than 500 prompt without knowing exactly how many (while still dividing aggregate statistics by 500). Also, we're giving the system infinitely more chances when it screws up. This messes up benchmarking. Plus, detecting error with `if "error" in output` does a string search over a potentially very long string, blocking the event loop, and I don't think it's that robust anyway. I think retrying should be removed and failed requests should be marked as failed in the result.

2024-02-17 16:06 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +        total_time=0,
You can assign default values to dataclass fields and you can avoid all these.
```python
@dataclass
class Foo:
    throughput: float = 0.0

Foo()
```

2024-02-17 16:08 UTC, jaywonchung commented on scripts/inference-server/local-tokenizers/mistral/chat_template.jinja
> +{% if (messages[0]['role'] != 'system') %}{{ raise_exception('First role should be system!') }}{% elif (messages[1]['role'] != 'user') %}{{ raise_exception('Second role should be user!') }}{% endif %
In general, for every file you commit, the files should end with a newline according to the UNIX specification. That's why GitHub is showing this red circle icon. Your editor should have a setting that controls line ending.

2024-02-18 01:55 UTC, ohjuny commented on scripts/inference-server/local-tokenizers/mistral/chat_template.jinja
> +{% if (messages[0]['role'] != 'system') %}{{ raise_exception('First role should be system!') }}{% elif (messages[1]['role'] != 'user') %}{{ raise_exception('Second role should be user!') }}{% endif %
Added new line.

>  Your editor should have a setting that controls line ending.
Not sure what you mean here. Does this mean a setting that automatically adds a trailing newline at the end of files?

2024-02-18 01:56 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +                break
This was originally in the vllm code. I just tried running a modified version (to report faliure) on 500 requests, and none seem to fail.

If we want to mark failed requests without retrying, do you have suggestions for a better way to check for failure than `"error" in output`?

2024-02-18 01:59 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +                break
Checking the response's status code?

2024-02-18 01:59 UTC, jaywonchung commented on scripts/inference-server/local-tokenizers/mistral/chat_template.jinja
> +{% if (messages[0]['role'] != 'system') %}{{ raise_exception('First role should be system!') }}{% elif (messages[1]['role'] != 'user') %}{{ raise_exception('Second role should be user!') }}{% endif %
Yeah. If your editor is VSCode, search for "vscode line ending setting."

2024-02-18 02:02 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +        total_time=0,
My only hesitation is that now the long list `results` is not at the end, which makes it "less nice" to look at the json, but I think this is fine. Marking resolved.

2024-02-18 02:08 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +                break
I'm not super familiar with status codes off the top of my head, but would a simple `status_code != 200` suffice?

2024-02-18 02:09 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +                break
Looking [here](https://umbraco.com/knowledge-base/http-status-codes/#2xx) suggests maybe any 2xx should be counted as success.

2024-02-18 02:13 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +                break
Yeah `200 <= code < 300` is a typical check.

2024-02-18 02:16 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +        total_time=0,
Uh wait, I think we may be talking about different things. I meant lines 170 to 186 can be removed by setting default values in the definition of the `Results` dataclass. Since we want to pre-allocate all the memory for `results` (which is a great idea), we will still instantiate `Results` like `Results(results=[Result() for _ in input_requests])`.

2024-02-18 02:17 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +        total_time=0,
Will this change anything about the generated JSON?

2024-02-18 02:30 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +                break
Based on empirical tests, successful requests seem to have status 200, and failed ones (where I intentionally corrupt the request) report 422. Created [deea45b](https://github.com/ml-energy/leaderboard/pull/34/commits/deea45b2fb358d1705f48cf823cdb9ce277147c7) to implement based on this info.

2024-02-18 02:34 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +        total_time=0,
It seems that the JSON orders fields by the order they appear in our definition of `Results`, and in a dataclass we can only define fields with default values after all fields without default values. Since the `results` field cannot be created with a default value (since the number of inputs is not known), we have to define it before all the other fields with default values, meaning it will show up before the other fields in the generated JSON.

A hacky way around this is to define `results` as `[]` by default, but this seems bad because it suggests that it is fine to leave `results` empty.

2024-02-18 02:36 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +        total_time=0,
Actually it's fine to default to an empty list, and IMO it doesn't suggest anything. Use `default_factory=list`: https://docs.python.org/3/library/dataclasses.html#dataclasses.field

2024-02-18 02:41 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +        total_time=0,
Sounds good, addressed in [cc2a0bf](https://github.com/ml-energy/leaderboard/pull/34/commits/cc2a0bfbff29ebd707dead564e5d149b941e51c8), tested locally.

2024-02-18 03:56 UTC, jaywonchung requested changes
Thanks for your work. I took a deep end-to-end look.

2024-02-18 03:56 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +        f.write(json.dumps(asdict(results)))
```suggestion
        f.write(json.dumps(asdict(results), indent=2))
```

2024-02-18 03:56 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +        "--external-energy",
Never used?

2024-02-18 03:56 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +    parser.add_argument(
Never used?

2024-02-18 03:56 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +    if backend in ["tgi", "vllm"]:
Move the check to the beginning of `run_benchmark`. We want this function to do as little blocking work as possible. You would have seen actual throughput being 0.49 when the given request rate was 0.50, even when the server was not saturated. That 0.01 is coming from small overhead in the benchmarking script aggregated.

2024-02-18 03:56 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +    request_end_time = time.perf_counter()
Shouldn't this move to line 122? Processing the returned bytes into `output` shouldn't count as the server's response time.

2024-02-18 03:56 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +    print(args)
Save as file as well, in a path derived from `args.out_name`.

2024-02-18 03:56 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +        print(f"(Server) Energy per token: {results.server_energy_per_output_token:.2f} J")
(Zeus) and (server) are confusing. Both are Zeus.

2024-02-18 03:56 UTC, jaywonchung commented on scripts/inference-server/local-tokenizers/Llama-2-70b-chat-hf/tokenizer_config.json
There are so many fields defined in the [original llama 2 tokenizer configuration file](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/blob/main/tokenizer_config.json). Things like `padding_side` or `tokenizer_class` actually look important. Why were all of those removed?

2024-02-18 03:56 UTC, jaywonchung commented on scripts/inference-server/local-tokenizers/mistral/chat_template.jinja
1. Directory names should be consistent with the models' huggingface hub path. For instance, this should be `local-tokenizers/mistralai/Mistral-7B-Instruct-v0.2/` (yes, two levels of directories). Same for llama.
2. Why does only Mistral have a Jinja file but not llama?

2024-02-18 03:56 UTC, jaywonchung commented on scripts/inference-server/local-tokenizers/README.md
> +There is a [known bug with TGI](https://github.com/huggingface/text-generation-inference/issues/1534) in which the default `tokenizer_config.json` is not handled properly by TGI by applying chat temp
Why is it fine to just remove that `.split()` call? What does it do? What if it breaks the chat template? If so, shouldn't we use a fixed version of TGI to benchmark?

2024-02-18 14:42 UTC, ohjuny reviewed
Answered questions, didn't address the requested changes.

2024-02-18 14:42 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +        "--external-energy",
This was initially there before vllm was instrumented. I guess we can remove it now if we want to, or if we potentially want to use other inference serving systems in the future we can leave it in. If we keep it in, I guess it now makes sense to make it default to True.

2024-02-18 14:42 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +    parser.add_argument(
This was in the starter code, and I didn't really dive into what it was doing. Removing it shouldn't affect our code.

2024-02-18 14:42 UTC, ohjuny commented on scripts/inference-server/local-tokenizers/Llama-2-70b-chat-hf/tokenizer_config.json
The TGI implementation of chat template discards everything except the 3 fields that I left. ChatTemplate is defined [here](https://github.com/huggingface/text-generation-inference/blob/main/router/src/infer.rs#L310) and initialized [here](https://github.com/huggingface/text-generation-inference/blob/main/router/src/infer.rs#L87).

For vLLM, they don't allow you to specify a `tokenizer_config.json` in the first place; but you can specify the template string as a file. This is why, for Mistral, I've included just the `chat_template.jinja`. Note that this was not needed for vLLM/Llama-2 because the vLLM implementation seems to handle the "actual" `tokenizer_config.json` (including the chat template) fine.

2024-02-18 14:42 UTC, ohjuny commented on scripts/inference-server/local-tokenizers/README.md
> +There is a [known bug with TGI](https://github.com/huggingface/text-generation-inference/issues/1534) in which the default `tokenizer_config.json` is not handled properly by TGI by applying chat temp
That's actually a typo, my bad. It should say `.strip()` (not split), which removes leading and trailing whitespace. My understanding was this is for "weird" prompts that have a lot of unnecessary whitespace, but our benchmark doesn't contain prompts like this, so I thought it would be fine.

For reference, here's the original unmodified tokenizer_config.json:
```
{
  "add_bos_token": true,
  "add_eos_token": false,
  "bos_token": {
    "__type": "AddedToken",
    "content": "<s>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "chat_template": "{% if messages[0]['role'] == 'system' %}{% set loop_messages = messages[1:] %}{% set system_message = messages[0]['content'] %}{% else %}{% set loop_messages = messages %}{% set system_message = false %}{% endif %}{% for message in loop_messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if loop.index0 == 0 and system_message != false %}{% set content = '<<SYS>>\\n' + system_message + '\\n<</SYS>>\\n\\n' + message['content'] %}{% else %}{% set content = message['content'] %}{% endif %}{% if message['role'] == 'user' %}{{ bos_token + '[INST] ' + content.strip() + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ ' '  + content.strip() + ' ' + eos_token }}{% endif %}{% endfor %}",
  "clean_up_tokenization_spaces": false,
  "eos_token": {
    "__type": "AddedToken",
    "content": "</s>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  },
  "legacy": false,
  "model_max_length": 1000000000000000019884624838656,
  "pad_token": null,
  "padding_side": "right",
  "sp_model_kwargs": {},
  "tokenizer_class": "LlamaTokenizer",
  "unk_token": {
    "__type": "AddedToken",
    "content": "<unk>",
    "lstrip": false,
    "normalized": false,
    "rstrip": false,
    "single_word": false
  }
}
```
and the original unmodified chat template:
```
{% if messages[0]['role'] == 'system' %}
    {% set loop_messages = messages[1:] %}
    {% set system_message = messages[0]['content'] %}
{% else %}
    {% set loop_messages = messages %}
    {% set system_message = false %}
{% endif %}
{% for message in loop_messages %}
    {% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}
        {{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}
    {% endif %}
    {% if loop.index0 == 0 and system_message != false %}
        {% set content = '<<SYS>>\\n' + system_message + '\\n<</SYS>>\\n\\n' + message['content'] %}
    {% else %}
        {% set content = message['content'] %}
    {% endif %}
    {% if message['role'] == 'user' %}
        {{ bos_token + '[INST] ' + content.strip() + ' [/INST]' }}
    {% elif message['role'] == 'assistant' %}
        {{ ' '  + content.strip() + ' ' + eos_token }}
    {% endif %}
{% endfor %}
```
The 2 calls to `content.strip()` were modified to just `content`.

2024-02-18 14:42 UTC, ohjuny commented on scripts/inference-server/local-tokenizers/mistral/chat_template.jinja
2. Copy pasting response from another review comment:

For vLLM, they don't allow you to specify a tokenizer_config.json in the first place; but you can specify the template string as a file. This is why, for Mistral, I've included just the chat_template.jinja. Note that this was not needed for vLLM/Llama-2 because the vLLM implementation seems to handle the "actual" tokenizer_config.json (including the chat template) fine.

2024-02-18 14:42 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +    request_end_time = time.perf_counter()
I think this is an artifact of the original "retry on failure" approach (they originally wanted the latency when the request eventually succeeds). Given that we don't do this anymore, it should be fine to move to line 122.

2024-02-18 14:42 UTC, ohjuny commented on scripts/inference-server/benchmark.py
> +        print(f"(Server) Energy per token: {results.server_energy_per_output_token:.2f} J")
Yeah I couldn't think of a good name... I considered "Individual Responses" but that seems like a mouthful. We could also do "Local Zeus" vs "External Zeus"... any ideas?

2024-02-18 14:44 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +        "--external-energy",
Let's remove.

2024-02-18 14:44 UTC, jaywonchung commented on scripts/inference-server/benchmark.py
> +    parser.add_argument(
Let's remove this as well.

2024-02-18 14:48 UTC, jaywonchung commented on scripts/inference-server/local-tokenizers/Llama-2-70b-chat-hf/tokenizer_config.json
I would still just copy the entire config and modify the minimum parts that are needed to be safe. After all, in the future, TGI might use more fields.

2024-02-18 14:51 UTC, jaywonchung commented on scripts/inference-server/local-tokenizers/README.md
> +There is a [known bug with TGI](https://github.com/huggingface/text-generation-inference/issues/1534) in which the default `tokenizer_config.json` is not handled properly by TGI by applying chat temp
Hmm, I see. Fair enough. I'll just keep that in mind and try to roll back to the original tokenizer config when TGI releases a new version with a fix.

2024-02-18 14:51 UTC, jaywonchung commented on scripts/inference-server/local-tokenizers/README.md
> +There is a [known bug with TGI](https://github.com/huggingface/text-generation-inference/issues/1534) in which the default `tokenizer_config.json` is not handled properly by TGI by applying chat temp
BTW all this I'm assuming that you visually inspected the responses of llama/mistral and they sorta made sense, right?

2024-02-18 15:01 UTC, ohjuny commented on scripts/inference-server/local-tokenizers/Llama-2-70b-chat-hf/tokenizer_config.json
Updated, tested locally to check that TGI has no problem loading it with extraneous fields.

2024-02-18 15:50 UTC, jaywonchung approved these changes
LGTM! Thanks so much for your great work!

2024-02-18 15:50 UTC, merged