enable multiple setup/tables; add external table col
ml-energy/leaderboard-v2 pull request #6
Opened 2023-06-21 14:57 UTC by AmberLJC

Updates
- Enable multiple table display
- Add columns from external table
- The format of `benchmark.csv`: 
    - `A100_chat_benchmark.csv, A40_chat_benchmark.csv `
    - `A100_chat_benchmark` is a placeholder

2023-06-21 15:18 UTC, jaywonchung commented
Why do we need a separate file for the table manager? It's not getting reused anywhere, our code is not a proper Python module anyway, and the Gradio UI code is already tightly coupled with the implementation of the TableManager. Plus, with this, it's impossible to see any diffs from the PR and review. If this was going to be a module re-org, it should be been a separate PR.

2023-06-21 19:47 UTC, jaywonchung requested changes
Thank you for your work. I just skimmed the source code for now and left some comments.

2023-06-21 19:47 UTC, jaywonchung commented on app.py
> +import json
Inconsistent import ordering/spacing. Basically there should be four newline-separated blocks -- (1) Special imports like `__future__`, (2) built-in modules like `json`, (3) external packages like `pandas`, and (4) self-imports (which we currently do not have).

Ref: [PEP 8 Imports](https://peps.python.org/pep-0008/#imports)

2023-06-21 19:47 UTC, jaywonchung commented on app.py
> +        self.default_colname = self.dfs[self.cur_df_name].columns.tolist()[1:]
Didn't we discuss this yesterday and say we'll merge everything into a single DataFrame (with columns `gpu_type` and `task_type` or similar) and later filter it with `pandas.DataFrame.query` or similar in order to display? And the benefit of doing that was that now there isn't an index for each table. There's only one global index ordering.

2023-06-21 19:47 UTC, jaywonchung commented on app.py
> +        self.models = json.load(open(f"{data_dir}/models.json"))
IMO this should *not* be an instance variable. This dictionary is merely a temporary piece of data that we use to translate model names and read the number of parameters, which means that it is of no use after the dataframe is initialized. `TableManager` does not have to keep a reference to this.

2023-06-21 19:47 UTC, jaywonchung commented on app.py
> +    def __init__(self, data_dir: str, setup_list = ['A40_chat', 'A100_chat']) -> None:
This code assumes that files will be named `{setup}_banchmark.csv`. When we get more and more GPU types and task types, and potentially add more dimensions (like PyTorch vs TensorRT), the `data` directory will get flooded with CSV files with long names. Even worse, old `data` directories will break because when we add PyTorch vs TensorRT, those old directories will not have stuff named as `A40_chat_pytorch_benchmark.csv`.

There should be a more programmatic & easier-to-change way to define extra dimensions not specified in the benchmark CSV files.

2023-06-21 19:47 UTC, jaywonchung commented on app.py
> +        return self.dfs[self.cur_df_name]
We want one big DataFrame, but even if you were going to do this, you should have implemented an `@property` in `TableManager` called `df` and have it return `self.dfs[self.cur_df_name]`, instead of repeating this everywhere. Remember the DRY principle.

2023-06-21 19:47 UTC, jaywonchung commented on app.py
> +            setup_radio.change(fn = global_tbm.switch_table, inputs = setup_radio, outputs = dataframe)
You should **never** modify the global instance. See doc for gr.State and my comment in the 'Improve Gradio' PR. The global_tbm object is read only for data that will not change across all the users of the leaderboard throughout the lifetime of the Gradio app.

I see a couple more references to global_tbm below. Please make sutre they're all correct.

2023-06-21 19:47 UTC, jaywonchung commented on app.py
> +            # formula_input.submit(global_tbm.add_column, inputs=[tbm, colname_input, formula_input], outputs=[dataframe, add_col_message])
What were these changes? Also, please remove unused code instead of commenting them out.

2023-06-21 19:54 UTC, AmberLJC commented on app.py
> +        self.default_colname = self.dfs[self.cur_df_name].columns.tolist()[1:]
I think how user will add these columns to construct their table matters. Let them input `sql query` is too demanding, instead use dropdown to select the setup would be easier. 
Can you remind me why `there isn't an index for each table` is a benefit?

2023-06-21 20:06 UTC, AmberLJC commented on app.py
> +    def __init__(self, data_dir: str, setup_list = ['A40_chat', 'A100_chat']) -> None:
Yea, we can just list any `{setup}_banchmark.csv` from the directory as the input to `TableManager`. 

Alternative is to merge all `.csv`, but just a bit hard to maintain the table incrementally.  wdyt

For extra dimensions, naive solution is to split the file name `A40_chat_pytorch_benchmark`.

2023-06-21 20:09 UTC, AmberLJC commented on app.py
> +            setup_radio.change(fn = global_tbm.switch_table, inputs = setup_radio, outputs = dataframe)
I will check it later. (I might code something wrong so I have to do this to update the table.)

2023-06-21 20:13 UTC, jaywonchung commented on app.py
> +            setup_radio.change(fn = global_tbm.switch_table, inputs = setup_radio, outputs = dataframe)
You can keep the fn TableManager.switch_table and add the dataframe gr.Dataframe object as the first element of inputs. That works because
```python
obj = Foo()
obj.method()
```
is just syntactic sugar for
```python
obj = Foo()
Foo.method(obj)
```

2023-06-22 19:49 UTC, jaywonchung commented on app.py
> +    def __init__(self, data_dir: str, setup_list = ['A40_chat', 'A100_chat']) -> None:
Offline discussion:

`data/2023-06-17/schema.json`:
```json
{
  "gpu": ["A40"],
  "task": ["chat", "chat-concise", "instruct", "instruct-concise"]
}
```

1. Read from `schema.json`.
2. For each key (e.g., gpu, task), create a `gr.Dropdown` on top of the table, each with choices as defined in the JSON file.
3. For each cartesian product of the choice, there may or may not be a `benchmark.csv` file. Something like:
    ```python
    files = []
    for keys in itertools.product(*all_key_choices):
        with contextlib.suppress(FileNotFoundError):
            df = pd.read_csv("_".join(keys) + "_benchmark.csv")
            big_df = big_df.merge(df)
    ```

2023-06-22 20:26 UTC, jaywonchung commented
@AmberLJC Pushed three more benchmark CSV files and `schema.json`!

2023-06-22 20:55 UTC, jaywonchung commented
@AmberLJC Oh I just realized that keys in JSON dictionaries are not ordered. Loading the current schema.json, gpu and task will not have a guaranteed ordering in the dictionary and we still don't to hard code anything in app.py. You should probably change schema.json so that it's something like:

```json
[
  {"gpu": ["A40"]},
  {"task": []}
]

```

2023-06-22 23:13 UTC, AmberLJC commented
Should I consider the scenario such as:
> I have only A100+PyTorch, A100+ tensorflow , A10+PyTorch. Since A10+ tensorflow is missing, I should avoid users to pick such combination from the radio button. 

In that case, it's just easier to read all `*_benchmark.csv` from the directory or specify that in `schema.json`

2023-06-22 23:18 UTC, jaywonchung commented
> Should I consider the scenario such as:
> 
> > I have only A100+PyTorch, A100+ tensorflow , A10+PyTorch. Since A10+ tensorflow is missing, I should avoid users to pick such combination from the radio button.

I think `schema.json` should specify every possible choices of each key. But as you said, some combinations of choices will not exist, and that's why I had `with contextlib.suppress(FileNotFoundError):` in the comment.

> In that case, it's just easier to read all `*_benchmark.csv` from the directory or specify that in `schema.json`

I disagree with that one. Then you have to read a file and look at the name of the file to determine what the value of `gpu`, `task`, etc should be. To do that, you pretty much have to `split("_")`, which prevents us from having an underscore in the possible choices of any key.

2023-06-22 23:24 UTC, AmberLJC commented
okay `FileNotFoundError` make my life easier.   updating the button based on the existence of `csv` file is feasible but a bit complicated. and we can just try to have all combinations available

2023-06-22 23:26 UTC, jaywonchung commented
Yeah if a user selects a combination that we don't have, the table will show zero rows and they'll know.

2023-06-22 23:27 UTC, AmberLJC commented
one more thing to confirm with you, how do you want to name the column if two tables are displayed. such as `thoughput_A100`, `thoughput_A40`? but you know the name will get longer if we have more setups

2023-06-22 23:29 UTC, jaywonchung commented
Um I thought column names don't have to change. They can just stay as `throughput`, `response_length`, etc and there are two more columns: `gpu` and `task` right next to `model`.

2023-06-22 23:33 UTC, AmberLJC commented
model | gpu | task | throughput  | gpu | task | throughput | 
|--------|------|------|---------------|------|------|------------|
|model1 | A40 | chat | 20 | A100 | chat | 40 |


 


 like this? and how to add custom column then, how to specify the target energy column to operate

2023-06-22 23:38 UTC, jaywonchung commented
On first load:

model | gpu | task | throughput  | response_length|
|--------|------|------|---------------|--|
|model1 | A40 | chat | 20 | 100 |
|model1 |A100 | chat | 40 | 100 |
|model1 | A40 | chat-concise | 20 | 80 |
|model1 |A100 | chat-concise | 40 | 80 |
 
When the user picks `A100` from the dropdown, the table will be filtered to:

model | gpu | task | throughput  | response_length|
|--------|------|------|---------------|--|
|model1 |A100 | chat | 40 | 100 |
|model1 |A100 | chat-concise | 40 | 80 |

Further selecting `chat-concise` for `task`:

model | gpu | task | throughput  | response_length|
|--------|------|------|---------------|--|
|model1 |A100 | chat-concise | 40 | 80 |

2023-06-22 23:41 UTC, AmberLJC commented
Got it, thanks

2023-06-22 23:42 UTC, jaywonchung commented
But doing this, I realized that due to random seed differences, response length will be different on each GPU.
But it's also true that it's incredibly difficult to get true determinism with PyTorch and GPUs even when everything is the same... (ref: https://github.com/pytorch/pytorch/issues/7068) and I don't know what will happen when CUDA versions are different, GPU types are different, etc. Maybe we should just give up on this and use whatever number we get on each GPU. WDYT?

2023-06-22 23:43 UTC, jaywonchung commented
> and how to add custom column then, how to specify the target energy column to operate

Oh I missed your last sentence. When you add a custom column, it effectively operates on the entire table (the one we show on first load, and probably the one you have in `self.df`). Then we casually re-filter and show it based on the current dropdowns active.

2023-06-22 23:44 UTC, AmberLJC commented
Would the final number be very different  even after averaging thousands of response

2023-06-22 23:44 UTC, jaywonchung commented
> Would the final number be very different even after averaging thousands of response

Good point. I doubt it will be vastly different. I'll just mention that in the About tab.

2023-06-23 02:28 UTC, AmberLJC commented
Please check whether you need to improve any features.

2023-06-23 03:59 UTC, jaywonchung requested changes
This is awesome! Thank you for your effort. I left some comments.

2023-06-23 03:59 UTC, jaywonchung commented on app.py
> +import glob
Is this module used anywhere?

2023-06-23 03:59 UTC, jaywonchung commented on app.py
> +                    res_df = pd.concat([res_df, df])
Why did we do the entire `schema.json` or `schema.yaml` thing if you're just going to hard code GPU and task everywhere? We're not going to release the leaderboard before A100 results are out and we evaluate at least one NLP task metric, so it's not that this feature is on very tight deadline.

We debated between just hard coding fields in `app.py` vs. introducing a schema file to colocate all the dirty data and make `app.py` agnostic to the keys and choices we have, and chose the latter because it is easier to change in the future. But if you do this, you're getting the worst of both worlds; now we need to change `app.py` **and** the schema file together.

Also I don't get the `TODO`  comment. TODO for whom and when?

```python
schema: dict[str, list[str]] = yaml.safe_load()

res_df = pd.DataFrame()
for choice in itertools.product(*schema.values()):
    filepath = f"{data_dir}/{'_'.join(choice)}_benchmark.csv"
    with contextlib.suppress(FileNotFoundError):  # This is better than `os.path.exists` [1]
        df = pd.read_csv(filepath)
        for key, val in zip(schema.keys(), choice):
            df[key] = val
        res_df = pd.concat([res_df, pd.merge(df_score, df, on=['model']).round(2)])
```

[1] https://devblogs.microsoft.com/python/idiomatic-python-eafp-versus-lbyl/

2023-06-23 03:59 UTC, jaywonchung commented on app.py
> +        # self.setup_list = list(schema.keys())
Try not to leave commented code hanging around.

2023-06-23 03:59 UTC, jaywonchung commented on data/2023-06-17/schema.yaml
> +
Try not to have empty lines at the beginning and end of files.

2023-06-23 03:59 UTC, jaywonchung commented on app.py
> +block.launch()
Lines should end with a newline, and your editor is configured in a non-POSIX-compliant manner.

POSIX defines a *line* as a series of characters terminated by a newline character, and thus it is a rule to ensure that files end with a newline. That's also why GitHub shows this red circled minus sign to signal that it's not right.

Assuming PyCharm, this will help: https://stackoverflow.com/questions/36043061/automatically-add-newline-on-save-in-pycharm

2023-06-23 03:59 UTC, jaywonchung commented on app.py
> +            # Block 2: Allow users to custom new columns.
```suggestion
            # Block 2: Allow users to add new columns.
```

2023-06-23 03:59 UTC, jaywonchung commented on app.py
> +                with gr.Box(scale=10):
I get this complain on my setup:
```
sys:1: UserWarning: You have unused kwarg parameters in Box, please remove them: {'scale': 10}
```
```suggestion
                with gr.Box():
```

2023-06-23 03:59 UTC, jaywonchung commented on app.py
> +        self.task_list = self.task_choice = schema['task']
You should just expose `self.schema` and have the outside world read that dictionary.

2023-06-23 03:59 UTC, jaywonchung commented on app.py
> +                fetch = gr.Button(value="Fetch")
(1) Remove all hard coded parts. (2) I believe you can remove the fetch button. Users clicking checkboxes can be detected with the `gr.CheckboxGroup.change` event. (3) I think every checkbox should be checked by default (since checking shows stuff in the table, and we show everything at the beginning).

Here:
```python
checkboxes = []
for key, choices in global_tbm.schema.items():
    # Specifying `value` makes everything checked by default.
    checkboxes.append(gr.CheckboxGroup(choices=choices, value=choices, label=key))
```

After `dataframe` is defined:
```python
# Table automatically updates when users check or uncheck any checkbox.
for checkbox in checkboxes:
    checkbox.change(TableManager.create_filter_df, inputs=[tbm, gpu_choice, task_choice], outputs=dataframe)
```

2023-06-23 03:59 UTC, jaywonchung commented on app.py
> +        columns = self.df.columns.tolist()[1:] # include gpu and task in the dropdown
I really like this idea! Now people can also visually compare GPU throughput side by side, for example.

2023-06-23 03:59 UTC, jaywonchung commented on app.py
> +    def create_filter_df(self, gpu_choice = None, task_choice = None ) -> pd.DataFrame:
I think this should just **become** `get_df`, shouldn't it? Also remove all hardcoded parts using `self.schema` and defining the signature like `def create_filter_df(self, *choices)`.

2023-06-23 16:04 UTC, jaywonchung commented on app.py
> +        self.cur_filter = filters if filters else self.cur_filter
```suggestion
        self.cur_filter = filters or self.cur_filter
```

2023-06-23 16:04 UTC, jaywonchung commented
Let me know when it's ready for another round of review

2023-06-23 16:24 UTC, jaywonchung requested changes
Really nice! This will be the final round of complains. Thanks a lot!

2023-06-23 16:24 UTC, jaywonchung commented on app.py
> +            return self.get_df(), self._format_msg("Please enter a formula.")
Ideally `get_def` itself should use `functools.lru_cache`, but since `gr.CheckboxGroup` returns a list of strings and a list is not a hashable type in Python, `lru_cache` will not work as is. But in any case, the return value of `self.get_df` should at least be cached at least inside one method, especially when it's being called without any arguments.

2023-06-23 16:24 UTC, jaywonchung commented on app.py
> +        text = self.get_df()["model"].apply(lambda x: x.split(">")[1].split("<")[0])
Same here: `self.get_df`.

2023-06-23 16:24 UTC, jaywonchung commented on app.py
> +        res_df = pd.merge(df_score, res_df, on=['model']).round(2)
Before this, you should check if `res_df` is empty. That would mean something went wrong and no benchmark CSV file were ever read. In that case, a `ValueError` would make sense and the gradio app should crash during init.

2023-06-24 04:23 UTC, merged